baseURL = "https://pawka.notrollsallowed.com/"
languageCode = "en-us"
title = "Pawka's diary"
theme = "cactus"
Paginate = 100

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[params]
showAllPostsOnHomePage = true

[taxonomies]
tag = "tags"
